name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Install Node.js and Yarn
      uses: actions/setup-node@v2
      with:
        node-version: '14'
        cache: 'yarn'
        
    - name: Install dependencies
      run: yarn install
      
    - name: Run backend tests
      run: yarn test --cwd backend
      
    - name: Build frontend
      run: yarn build --cwd My Messenger
      
